version: '3.3'

# MoviePilot 地址：https://github.com/jxxghp/MoviePilot

services:

  moviepilot:
    stdin_open: true
    tty: true
    container_name: moviepilot
    hostname: moviepilot
    networks:
      - moviepilot
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    volumes:
      - '/home/MoviePilot/media:/media'
      - '/home/MoviePilot/config:/config'
      - '/home/MoviePilot/core:/moviepilot/.cache/ms-playwright'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      # WEB服务端口，默认3000，可自行修改，不能与API服务端口冲突
      - 'NGINX_PORT=3000'
      # API服务端口，默认3001，可自行修改，不能与WEB服务端口冲突
      - 'PORT=3001'
      # 运行程序用户的uid，默认0
      - 'PUID=0'
      # 运行程序用户的gid，默认0
      - 'PGID=0'
      # 掩码权限，默认000，可以考虑设置为022
      - 'UMASK=000'
      # 时区
      - 'TZ=Asia/Shanghai'
      # 重启时自动更新，true/release/dev/false，默认release，需要能正常连接Github 注意：如果出现网络问题可以配置PROXY_HOST
      - 'MOVIEPILOT_AUTO_UPDATE=true'
      # 网络代理，访问themoviedb或者重启更新需要使用代理访问，格式为http(s)://ip:port、socks5://user:pass@host:port
      - 'PROXY_HOST='
      # 认证站点
      - 'AUTH_SITE=iyuu'
      - 'IYUU_SIGN='
      # 超级管理员用户名，默认admin，安装后使用该用户登录后台管理界面，注意：启动一次后再次修改该值不会生效，除非删除数据库文件！
      - 'SUPERUSER=admin'
      # API密钥，默认moviepilot，在媒体服务器Webhook、微信回调等地址配置中需要加上?token=该值，建议修改为复杂字符串
      - 'API_TOKEN=adAfs1123adf123aZaqwe2341'
      # 大内存模式，默认为false，开启后会增加缓存数量，占用更多的内存，但响应速度会更快
      - 'BIG_MEMORY_MODE=false'
      # DNS over HTTPS开关，true/false，默认true，开启后会使用DOH对api.themoviedb.org等域名进行解析，以减少被DNS污染的情况，提升网络连通性
      - 'DOH_ENABLE=true'
      # 元数据识别缓存过期时间（小时），数字型，不配置或者配置为0时使用系统默认（大内存模式为7天，否则为3天），调大该值可减少themoviedb的访问次数
      - 'META_CACHE_EXPIRE='
      # Github token，提高自动更新、插件安装等请求Github Api的限流阈值，格式：ghp_****
      - 'GITHUB_TOKEN='
      # 开发者模式，true/false，默认false，开启后会暂停所有定时任务
      - 'DEV=false'
      # debug模式，开启后会输出debug日志
      - 'DEBUG=false'
      # 启动时自动检测和更新资源包（站点索引及认证等），true/false，默认true，需要能正常连接Github
      - 'AUTO_UPDATE_RESOURCE=true'
      # TMDB API地址，默认api.themoviedb.org，也可配置为api.tmdb.org、tmdb.movie-pilot.org 或其它中转代理服务地址，能连通即可
      - 'TMDB_API_DOMAIN=api.themoviedb.org'
      # TMDB图片地址，默认image.tmdb.org，可配置为其它中转代理以加速TMDB图片显示，如：static-mdb.v.geilijiasu.com
      - 'TMDB_IMAGE_DOMAIN=image.tmdb.org'
      # 登录首页电影海报，tmdb/bing，默认tmdb
      - 'WALLPAPER=tmdb'
      #  媒体信息识别来源，themoviedb/douban，默认themoviedb，使用douban时不支持二级分类
      - 'RECOGNIZE_SOURCE=themoviedb'
      # Fanart开关，true/false，默认true，关闭后刮削的图片类型会大幅减少
      - 'FANART_ENABLE=true'
      # 刮削元数据及图片使用的数据源，themoviedb/douban，默认themoviedb
      - 'SCRAP_SOURCE=themoviedb'
      # 新增已入库媒体是否跟随TMDB信息变化，true/false，默认true，为false时即使TMDB信息变化了也会仍然按历史记录中已入库的信息进行刮削
      - 'SCRAP_FOLLOW_TMDB=true'
      # 远程交互搜索时自动择优下载的用户ID（消息通知渠道的用户ID），多个用户使用,分割，设置为 all 代表全部用户自动择优下载，未设置需要手动选择资源或者回复0才自动择优下载
      - 'AUTO_DOWNLOAD_USER=all'
      # OCR识别服务器地址，格式：http(s)://ip:port，用于识别站点验证码实现自动登录获取Cookie等，不配置默认使用内建服务器https://movie-pilot.org
      - 'OCR_HOST=https://movie-pilot.org'
      # 下载站点字幕，true/false，默认truek
      - 'DOWNLOAD_SUBTITLE=true'
      # 搜索时是否使用多个名称搜索，true/false，默认true，开启后会使用多个名称进行搜索，搜索结果会更全面，但会增加搜索时间；关闭时只要其中一个名称搜索到结果或全部名称搜索完毕即停止
      - 'SEARCH_MULTIPLE_NAME=true'
      # 电影重命名格式
      - 'MOVIE_RENAME_FORMAT={{title}}{% if year %} ({{year}}){% endif %}/{{title}}{% if year %} ({{year}}){% endif %}{% if part %}-{{part}}{% endif %}{% if videoFormat %} - {{videoFormat}}{% endif %}{{fileExt}}'
      # 电视剧重命名格式
      - 'TV_RENAME_FORMAT={{title}}{% if year %} ({{year}}){% endif %}/Season {{season}}/{{title}} - {{season_episode}}{% if part %}-{{part}}{% endif %}{% if episode %} - 第 {{episode}} 集{% endif %}{{fileExt}}'
      # 插件市场仓库地址，仅支持Github仓库main分支，多个地址使用,分隔
      - 'PLUGIN_MARKET=https://github.com/jxxghp/MoviePilot-Plugins'
    logging:
      driver: json-file
      options:
        max-size: 5m
    restart: always
    image: jxxghp/moviepilot:latest

networks:
  moviepilot:
    name: moviepilot