version: '3.3'

# MoviePilot 地址：https://github.com/jxxghp/MoviePilot

services:
  moviepilot:
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
    environment:
      - 'PUID=0' # id -u
      - 'PGID=0' # id -g
      - 'UMASK=022'
      - 'TZ=Asia/Shanghai'
      # 重启更新
      - 'MOVIEPILOT_AUTO_UPDATE=release'
      # WEB服务端口
      - 'NGINX_PORT=3000'
      # 超级管理员用户名
      - 'SUPERUSER=lzq'
      # 超级管理员初始密码
      - 'SUPERUSER_PASSWORD=lionlinzq'
      # 登录首页电影海报，`tmdb`/`bing`，默认`tmdb`
      - 'WALLPAPER=tmdb'
      # API密钥，在媒体服务器Webhook、微信回调等地址配置中需要加上?token=该值，建议修改为复杂字符串
      - 'API_TOKEN=masZaepasdf123ilot'
      # 网络代理（可选）
      # - 'PROXY_HOST='
      # TMDB API地址
      - 'TMDB_API_DOMAIN=api.themoviedb.org'
      # 下载保存目录
      - 'DOWNLOAD_PATH=/media/downloads'
      - 'DOWNLOAD_MOVIE_PATH=/media/downloads/movies'
      - 'DOWNLOAD_TV_PATH=/media/downloads/tv'
      - 'DOWNLOAD_ANIME_PATH=/media/downloads/anime'
      # 下载站点字幕
      - 'DOWNLOAD_SUBTITLE=false'
      # 下载二级分类开关
      - 'DOWNLOAD_CATEGORY=false'
      # 下载器监控
      - 'DOWNLOADER_MONITOR=true'
      - 'SUBSCRIBE_MODE=spider'
      - 'SUBSCRIBE_RSS_INTERVAL=30'
      # 刮削入库的媒体文件
      - 'SCRAP_METADATA=true'
      - 'SCRAP_FOLLOW_TMDB=true'
      # 种子标签
      - 'TORRENT_TAG=MOVIEPILOT'
      # 媒体库目录
      - 'LIBRARY_PATH=/media'
      - 'LIBRARY_MOVIE_NAME=movies'
      - 'LIBRARY_TV_NAME=tv'
      - 'LIBRARY_ANIME_NAME=anime'
      # 媒体库二级分类开关
      - 'LIBRARY_CATEGORY=false'
      # 转移方式，支持link/copy/move/softlink
      - 'TRANSFER_TYPE=link'
      # 转移覆盖模式，默认为`size`，支持`nerver`/`size`/`always`，分别表示`不覆盖`/`根据文件大小覆盖（大覆盖小）`/`总是覆盖`
      - 'OVERWRITE_MODE=size'
      # CookieCloud服务器地址（默认可以不用修改）
      - 'COOKIECLOUD_HOST=http://<ip>:8088'
      # CookieCloud用户KEY
      - 'COOKIECLOUD_KEY=xxxxx'
      # CookieCloud端对端加密密码
      - 'COOKIECLOUD_PASSWORD=xxxxxx'
      # CookieCloud同步间隔（分钟）
      - 'COOKIECLOUD_INTERVAL=20'
      # CookieCloud对应的浏览器UA，可选，设置后可增加连接站点的成功率，同步站点后可以在管理界面中修改
      - 'USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36'
      - 'SUBSCRIBE_SEARCH=false'
      # 交互搜索自动下载用户ID，使用,分割
      - 'AUTO_DOWNLOAD_USER='

      # 插件市场仓库地址，多个地址使用`,`分隔，保留最后的/
      - 'PLUGIN_MARKET=https://raw.githubusercontent.com/jxxghp/MoviePilot-Plugins/main/'

      # 消息通知渠道，支持 telegram/wechat/slack/synologychat
      - 'MESSAGER=telegram'
      - 'TELEGRAM_TOKEN=xxxxxx'
      - 'TELEGRAM_CHAT_ID=xxxxxxxxxxxx'
      # - 'TELEGRAM_USERS=xxxxxxxxxxxxx'
      # - 'TELEGRAM_ADMINS=xxxxxxxxxxxxx'
      # - 'WECHAT_CORPID='
      # - 'WECHAT_APP_SECRET='
      # - 'WECHAT_APP_ID='
      # - 'WECHAT_TOKEN='
      # - 'WECHAT_ENCODING_AESKEY='
      # - 'WECHAT_ADMINS='
      # - 'WECHAT_PROXY='
      # - 'SLACK_OAUTH_TOKEN='
      # - 'SLACK_APP_TOKEN='
      # - 'SLACK_CHANNEL='
      # - 'SYNOLOGYCHAT_WEBHOOK='
      # - 'SYNOLOGYCHAT_TOKEN='

      # 下载器，支持qbittorrent/transmission
      - 'DOWNLOADER=qbittorrent'
      - 'QB_HOST=http://192.168.1.9:8127'
      - 'QB_USER=admin'
      - 'QB_PASSWORD=lionlinzq'
      - 'QB_CATEGORY=false'
      - 'QB_SEQUENTIAL=true'
      - 'QB_FORCE_RESUME=false'
      # - 'TR_HOST='
      # - 'TR_USER='
      # - 'TR_PASSWORD='

      # 媒体服务器，支持emby/jellyfin/plex
      - 'MEDIASERVER=emby'
      - 'EMBY_HOST=http://<ip>:8096'
      - 'EMBY_API_KEY=xxxxxxxxx'
      # - 'JELLYFIN_HOST='
      # - 'JELLYFIN_API_KEY='
      # - 'PLEX_HOST='
      # - 'PLEX_TOKEN='

      # 媒体服务器同步间隔（小时），默认`6`，留空则不同步
      - 'MEDIASERVER_SYNC_INTERVAL=6'
      # 媒体服务器同步黑名单，多个媒体库名称使用,分割
      - 'MEDIASERVER_SYNC_BLACKLIST='

      # 认证站点，认证资源`v1.0.1`支持`iyuu`/`hhclub`/`audiences`/`hddolby`/`zmpt`/`freefarm`/`hdfans`/`wintersakura`/`leaves`/`1ptba`/`icc2022`/`ptlsp`/`xingtan`/`ptvicomo`
      - 'AUTH_SITE=hdfans'
      - 'HDFANS_UID=xxxx'
      - 'HDFANS_PASSKEY=xxxxx'
      # 大内存模式
      - 'BIG_MEMORY_MODE=false'
      # 电影重命名格式
      - 'MOVIE_RENAME_FORMAT={{title}}{% if year %} ({{year}}){% endif %}/{{title}}{% if year %} ({{year}}){% endif %}{% if part %}-{{part}}{% endif %}{% if videoFormat %} - {{videoFormat}}{% endif %}{{fileExt}}'
      # 电视剧重命名格式
      - 'TV_RENAME_FORMAT={{title}}{% if year %} ({{year}}){% endif %}/Season {{season}}/{{title}} - {{season_episode}}{% if part %}-{{part}}{% endif %}{% if episode %} - 第 {{episode}} 集{% endif %}{{fileExt}}'
    restart: always
    tty: true
    volumes:
      - '/home/MoviePilot/media:/media'
      - '/home/MoviePilot/config:/config'
      - '/home/MoviePilot/core:/moviepilot/.cache/ms-playwright'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    network_mode: moviepilot
    hostname: moviepilot
    container_name: moviepilot
    image: 'jxxghp/moviepilot:latest'