server:
    port: 8080
    tomcat:
        max-connections: 8192
        threads:
            max: 200
            min-spare: 10

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.9:3306/base_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root
        hikari:
            maximum-pool-size: 50
            minimum-idle: 10                 # 根据业务波动调整
            connection-timeout: 60000        # 延长超时时间到60秒
            validation-timeout: 5000
            idle-timeout: 600000             # 空闲连接超时(10分钟)
            max-lifetime: 1800000            # 连接最大存活时间(30分钟)
            leak-detection-threshold: 60000  # 连接泄漏检测
            pool-name: MAIN-DB-POOL
            initialization-fail-timeout: 30000
            connection-init-sql: SELECT 1    # MySQL验证查询
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true

    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB


    jpa:
        show-sql: false
        hibernate:
            ddl-auto: none
    properties:
        hibernate:
            jdbc:
                #为spring data jpa saveAll方法提供批量插入操作 此处可以随时更改大小 建议500哦
                batch_size: 500
                batch_versioned_data: true
                order_inserts: true
                order_updates: true
                generate_statistics: true


#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

