server:
    port: 8080
    tomcat:
        threads:
            max: 2000  # 设置 Tomcat 最大线程数为 2000
            min-spare: 10  # 设置 Tomcat 最小空闲线程数为 10

spring:
    datasource:
        url: jdbc:mysql://192.168.1.9:3306/base_db?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
        username: root
        password: root  # 替换为你的数据库密码
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10  # 设置 Hikari 连接池的最大连接数
            minimum-idle: 5  # 设置 Hikari 连接池的最小空闲连接数

mybatis-plus:
    mapper-locations: classpath:mappers/*.xml  # MyBatis Mapper 文件路径
    type-aliases-package: pers.lionlinzq.excel.entity.mybatis.entity  # 实体类包路径
    configuration:
        map-underscore-to-camel-case: true  # 开启驼峰命名映射
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启 SQL 日志输出